/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseComponenteItem: typeof import('./src/components/Base/ComponenteItem.vue')['default']
    BaseConteudoEditavel: typeof import('./src/components/Base/ConteudoEditavel.vue')['default']
    BaseEditor: typeof import('./src/components/Base/Editor.vue')['default']
    ComponentesCard: typeof import('./src/components/Componentes/Card.vue')['default']
    ComponentesCardsCard: typeof import('./src/components/Componentes/Cards/Card.vue')['default']
    ComponentesGenericosCabecalho: typeof import('./src/components/Componentes/Genericos/Cabecalho.vue')['default']
    ComponentesGenericosColuna: typeof import('./src/components/Componentes/Genericos/Coluna.vue')['default']
    ComponentesGenericosConfiguracaoCabecalho: typeof import('./src/components/Componentes/Genericos/Configuracao/Cabecalho.vue')['default']
    ComponentesGenericosConfiguracaoColuna: typeof import('./src/components/Componentes/Genericos/Configuracao/Coluna.vue')['default']
    ComponentesGenericosConfiguracaoLinha: typeof import('./src/components/Componentes/Genericos/Configuracao/Linha.vue')['default']
    ComponentesGenericosLinha: typeof import('./src/components/Componentes/Genericos/Linha.vue')['default']
    ComponentesParagrafo: typeof import('./src/components/Componentes/Paragrafo.vue')['default']
    ComponentesParagrafosParagrafo: typeof import('./src/components/Componentes/Paragrafos/Paragrafo.vue')['default']
    ComponentesTitulo: typeof import('./src/components/Componentes/Titulo.vue')['default']
    ComponentesTitulosTitulo: typeof import('./src/components/Componentes/Titulos/Titulo.vue')['default']
    FerramentaColuna: typeof import('./src/components/Ferramenta/Coluna.vue')['default']
    FerramentaComponente: typeof import('./src/components/Ferramenta/Componente.vue')['default']
    FerramentaLinha: typeof import('./src/components/Ferramenta/Linha.vue')['default']
    Ferramentas: typeof import('./src/components/Ferramentas.vue')['default']
    MenuComponente: typeof import('./src/components/Menu/Componente.vue')['default']
    MenuConfiguracao: typeof import('./src/components/Menu/Configuracao.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
